# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mobile.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1938, 1958)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.FindSubstancesDb = QtWidgets.QGroupBox(self.centralwidget)
        self.FindSubstancesDb.setGeometry(QtCore.QRect(10, 0, 871, 821))
        self.FindSubstancesDb.setTitle("")
        self.FindSubstancesDb.setObjectName("FindSubstancesDb")
        self.FindName = QtWidgets.QLineEdit(self.FindSubstancesDb)
        self.FindName.setEnabled(True)
        self.FindName.setGeometry(QtCore.QRect(50, 60, 631, 51))
        self.FindName.setText("")
        self.FindName.setObjectName("FindName")
        self.FindFormula = QtWidgets.QLineEdit(self.FindSubstancesDb)
        self.FindFormula.setGeometry(QtCore.QRect(50, 150, 631, 51))
        self.FindFormula.setText("")
        self.FindFormula.setObjectName("FindFormula")
        self.FindSubstances = QtWidgets.QTableWidget(self.FindSubstancesDb)
        self.FindSubstances.setGeometry(QtCore.QRect(50, 230, 631, 581))
        self.FindSubstances.setObjectName("FindSubstances")
        self.FindSubstances.setColumnCount(4)
        self.FindSubstances.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.FindSubstances.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.FindSubstances.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.FindSubstances.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.FindSubstances.setHorizontalHeaderItem(3, item)
        self.ClearFind = QtWidgets.QPushButton(self.FindSubstancesDb)
        self.ClearFind.setGeometry(QtCore.QRect(700, 60, 121, 51))
        self.ClearFind.setObjectName("ClearFind")
        self.FindInfo1 = QtWidgets.QLabel(self.FindSubstancesDb)
        self.FindInfo1.setGeometry(QtCore.QRect(50, 110, 611, 41))
        self.FindInfo1.setObjectName("FindInfo1")
        self.FindInfo2 = QtWidgets.QLabel(self.FindSubstancesDb)
        self.FindInfo2.setGeometry(QtCore.QRect(60, 20, 601, 41))
        self.FindInfo2.setObjectName("FindInfo2")
        self.NewSubstanced = QtWidgets.QPushButton(self.FindSubstancesDb)
        self.NewSubstanced.setGeometry(QtCore.QRect(700, 150, 121, 51))
        self.NewSubstanced.setObjectName("NewSubstanced")
        self.ReactionCalculation = QtWidgets.QPushButton(self.FindSubstancesDb)
        self.ReactionCalculation.setGeometry(QtCore.QRect(700, 230, 121, 51))
        self.ReactionCalculation.setObjectName("ReactionCalculation")
        self.NewSubstenced = QtWidgets.QGroupBox(self.centralwidget)
        self.NewSubstenced.setGeometry(QtCore.QRect(10, 0, 871, 821))
        self.NewSubstenced.setTitle("")
        self.NewSubstenced.setObjectName("NewSubstenced")
        self.TITLE_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.TITLE_2.setGeometry(QtCore.QRect(320, 30, 311, 81))
        self.TITLE_2.setObjectName("TITLE_2")
        self.NewSubstanceHF = QtWidgets.QLineEdit(self.NewSubstenced)
        self.NewSubstanceHF.setGeometry(QtCore.QRect(360, 220, 201, 31))
        self.NewSubstanceHF.setObjectName("NewSubstanceHF")
        self.NewSubstanceSF = QtWidgets.QLineEdit(self.NewSubstenced)
        self.NewSubstanceSF.setGeometry(QtCore.QRect(360, 270, 201, 31))
        self.NewSubstanceSF.setObjectName("NewSubstanceSF")
        self.NewSubstanceGF = QtWidgets.QLineEdit(self.NewSubstenced)
        self.NewSubstanceGF.setGeometry(QtCore.QRect(360, 314, 201, 31))
        self.NewSubstanceGF.setObjectName("NewSubstanceGF")
        self.TextH_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.TextH_2.setGeometry(QtCore.QRect(50, 220, 311, 31))
        self.TextH_2.setObjectName("TextH_2")
        self.TextS_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.TextS_2.setGeometry(QtCore.QRect(50, 270, 311, 31))
        self.TextS_2.setObjectName("TextS_2")
        self.TextG_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.TextG_2.setGeometry(QtCore.QRect(50, 310, 311, 41))
        self.TextG_2.setObjectName("TextG_2")
        self.TextCp_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.TextCp_2.setGeometry(QtCore.QRect(50, 356, 311, 31))
        self.TextCp_2.setObjectName("TextCp_2")
        self.SiH_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.SiH_2.setGeometry(QtCore.QRect(560, 220, 101, 31))
        self.SiH_2.setObjectName("SiH_2")
        self.SiS_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.SiS_2.setGeometry(QtCore.QRect(560, 270, 101, 31))
        self.SiS_2.setObjectName("SiS_2")
        self.SiG_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.SiG_2.setGeometry(QtCore.QRect(560, 320, 101, 21))
        self.SiG_2.setObjectName("SiG_2")
        self.SiCp_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.SiCp_2.setGeometry(QtCore.QRect(560, 350, 101, 31))
        self.SiCp_2.setObjectName("SiCp_2")
        self.NewNameSubstance = QtWidgets.QLineEdit(self.NewSubstenced)
        self.NewNameSubstance.setGeometry(QtCore.QRect(52, 124, 611, 81))
        self.NewNameSubstance.setObjectName("NewNameSubstance")
        self.NewSubstanceState = QtWidgets.QComboBox(self.NewSubstenced)
        self.NewSubstanceState.setGeometry(QtCore.QRect(690, 220, 131, 41))
        self.NewSubstanceState.setObjectName("NewSubstanceState")
        self.NewSubstanceState.addItem("")
        self.NewSubstanceState.addItem("")
        self.NewSubstanceState.addItem("")
        self.SaveNewSubstance = QtWidgets.QPushButton(self.NewSubstenced)
        self.SaveNewSubstance.setGeometry(QtCore.QRect(690, 120, 131, 81))
        self.SaveNewSubstance.setObjectName("SaveNewSubstance")
        self.CancleNewSubstance = QtWidgets.QPushButton(self.NewSubstenced)
        self.CancleNewSubstance.setGeometry(QtCore.QRect(690, 60, 131, 51))
        self.CancleNewSubstance.setObjectName("CancleNewSubstance")
        self.Formula_2 = QtWidgets.QLabel(self.NewSubstenced)
        self.Formula_2.setGeometry(QtCore.QRect(50, 400, 131, 41))
        self.Formula_2.setObjectName("Formula_2")
        self.newFomulaSubstanced = QtWidgets.QLineEdit(self.NewSubstenced)
        self.newFomulaSubstanced.setGeometry(QtCore.QRect(182, 400, 381, 41))
        self.newFomulaSubstanced.setObjectName("newFomulaSubstanced")
        self.NewSubstanceCp = QtWidgets.QLineEdit(self.NewSubstenced)
        self.NewSubstanceCp.setGeometry(QtCore.QRect(360, 360, 201, 31))
        self.NewSubstanceCp.setObjectName("NewSubstanceCp")
        self.Result = QtWidgets.QLabel(self.NewSubstenced)
        self.Result.setGeometry(QtCore.QRect(700, 290, 141, 71))
        self.Result.setObjectName("Result")
        self.System = QtWidgets.QGroupBox(self.centralwidget)
        self.System.setGeometry(QtCore.QRect(10, 0, 871, 821))
        self.System.setTitle("")
        self.System.setObjectName("System")
        self.Substanced = QtWidgets.QLineEdit(self.System)
        self.Substanced.setGeometry(QtCore.QRect(30, 180, 681, 61))
        self.Substanced.setObjectName("Substanced")
        self.StartTemperatura = QtWidgets.QLineEdit(self.System)
        self.StartTemperatura.setGeometry(QtCore.QRect(170, 280, 101, 31))
        self.StartTemperatura.setObjectName("StartTemperatura")
        self.StartPressure = QtWidgets.QLineEdit(self.System)
        self.StartPressure.setGeometry(QtCore.QRect(170, 330, 101, 31))
        self.StartPressure.setObjectName("StartPressure")
        self.StartSize = QtWidgets.QLineEdit(self.System)
        self.StartSize.setGeometry(QtCore.QRect(170, 380, 101, 31))
        self.StartSize.setObjectName("StartSize")
        self.label = QtWidgets.QLabel(self.System)
        self.label.setGeometry(QtCore.QRect(60, 280, 121, 31))
        self.label.setObjectName("label")
        self.label_1 = QtWidgets.QLabel(self.System)
        self.label_1.setGeometry(QtCore.QRect(60, 330, 111, 31))
        self.label_1.setObjectName("label_1")
        self.label_3 = QtWidgets.QLabel(self.System)
        self.label_3.setGeometry(QtCore.QRect(26, 376, 141, 31))
        self.label_3.setObjectName("label_3")
        self.ConstTemeratura = QtWidgets.QCheckBox(self.System)
        self.ConstTemeratura.setGeometry(QtCore.QRect(281, 280, 131, 31))
        self.ConstTemeratura.setObjectName("ConstTemeratura")
        self.ConstSize = QtWidgets.QCheckBox(self.System)
        self.ConstSize.setGeometry(QtCore.QRect(281, 380, 131, 31))
        self.ConstSize.setChecked(True)
        self.ConstSize.setObjectName("ConstSize")
        self.ConstPressure = QtWidgets.QCheckBox(self.System)
        self.ConstPressure.setGeometry(QtCore.QRect(281, 332, 131, 31))
        self.ConstPressure.setObjectName("ConstPressure")
        self.EndSize = QtWidgets.QLineEdit(self.System)
        self.EndSize.setGeometry(QtCore.QRect(460, 380, 101, 31))
        self.EndSize.setObjectName("EndSize")
        self.EndPressure = QtWidgets.QLineEdit(self.System)
        self.EndPressure.setGeometry(QtCore.QRect(460, 330, 101, 31))
        self.EndPressure.setObjectName("EndPressure")
        self.EndTemperatura = QtWidgets.QLineEdit(self.System)
        self.EndTemperatura.setGeometry(QtCore.QRect(460, 280, 101, 31))
        self.EndTemperatura.setObjectName("EndTemperatura")
        self.label_2 = QtWidgets.QLabel(self.System)
        self.label_2.setGeometry(QtCore.QRect(150, 250, 191, 17))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.System)
        self.label_4.setGeometry(QtCore.QRect(430, 250, 161, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.System)
        self.label_5.setGeometry(QtCore.QRect(270, 140, 261, 17))
        self.label_5.setObjectName("label_5")
        self.Calculation = QtWidgets.QPushButton(self.System)
        self.Calculation.setGeometry(QtCore.QRect(730, 180, 111, 61))
        self.Calculation.setObjectName("Calculation")
        self.ResultReaction = QtWidgets.QFrame(self.System)
        self.ResultReaction.setGeometry(QtCore.QRect(60, 440, 621, 251))
        self.ResultReaction.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.ResultReaction.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ResultReaction.setObjectName("ResultReaction")
        self.label_6 = QtWidgets.QLabel(self.ResultReaction)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 81, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.ResultReaction)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 171, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.ResultReaction)
        self.label_8.setGeometry(QtCore.QRect(30, 50, 171, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.ResultReaction)
        self.label_9.setGeometry(QtCore.QRect(30, 70, 201, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.ResultReaction)
        self.label_10.setGeometry(QtCore.QRect(30, 110, 211, 17))
        self.label_10.setObjectName("label_10")
        self.dH = QtWidgets.QLabel(self.ResultReaction)
        self.dH.setGeometry(QtCore.QRect(200, 30, 231, 17))
        self.dH.setObjectName("dH")
        self.dS = QtWidgets.QLabel(self.ResultReaction)
        self.dS.setGeometry(QtCore.QRect(190, 50, 231, 17))
        self.dS.setObjectName("dS")
        self.dG = QtWidgets.QLabel(self.ResultReaction)
        self.dG.setGeometry(QtCore.QRect(230, 70, 231, 17))
        self.dG.setObjectName("dG")
        self.Kp = QtWidgets.QLabel(self.ResultReaction)
        self.Kp.setGeometry(QtCore.QRect(220, 110, 67, 17))
        self.Kp.setObjectName("Kp")
        self.BackCalculation = QtWidgets.QPushButton(self.System)
        self.BackCalculation.setGeometry(QtCore.QRect(730, 60, 111, 51))
        self.BackCalculation.setObjectName("BackCalculation")
        self.SubstancesInfo = QtWidgets.QGroupBox(self.centralwidget)
        self.SubstancesInfo.setGeometry(QtCore.QRect(10, 0, 871, 821))
        self.SubstancesInfo.setTitle("")
        self.SubstancesInfo.setObjectName("SubstancesInfo")
        self.TITLE = QtWidgets.QLabel(self.SubstancesInfo)
        self.TITLE.setGeometry(QtCore.QRect(320, 30, 311, 81))
        self.TITLE.setObjectName("TITLE")
        self.backFindDB = QtWidgets.QPushButton(self.SubstancesInfo)
        self.backFindDB.setGeometry(QtCore.QRect(688, 60, 131, 51))
        self.backFindDB.setObjectName("backFindDB")
        self.EditionSubstanceHF = QtWidgets.QLineEdit(self.SubstancesInfo)
        self.EditionSubstanceHF.setGeometry(QtCore.QRect(360, 220, 201, 31))
        self.EditionSubstanceHF.setObjectName("EditionSubstanceHF")
        self.EditionSubstanceSF = QtWidgets.QLineEdit(self.SubstancesInfo)
        self.EditionSubstanceSF.setGeometry(QtCore.QRect(360, 270, 201, 31))
        self.EditionSubstanceSF.setObjectName("EditionSubstanceSF")
        self.EditionSubstanceGF = QtWidgets.QLineEdit(self.SubstancesInfo)
        self.EditionSubstanceGF.setGeometry(QtCore.QRect(360, 314, 201, 31))
        self.EditionSubstanceGF.setObjectName("EditionSubstanceGF")
        self.TextH = QtWidgets.QLabel(self.SubstancesInfo)
        self.TextH.setGeometry(QtCore.QRect(50, 220, 311, 31))
        self.TextH.setObjectName("TextH")
        self.TextS = QtWidgets.QLabel(self.SubstancesInfo)
        self.TextS.setGeometry(QtCore.QRect(50, 270, 311, 31))
        self.TextS.setObjectName("TextS")
        self.TextG = QtWidgets.QLabel(self.SubstancesInfo)
        self.TextG.setGeometry(QtCore.QRect(50, 310, 311, 41))
        self.TextG.setObjectName("TextG")
        self.TextCp = QtWidgets.QLabel(self.SubstancesInfo)
        self.TextCp.setGeometry(QtCore.QRect(50, 356, 311, 31))
        self.TextCp.setObjectName("TextCp")
        self.SiH = QtWidgets.QLabel(self.SubstancesInfo)
        self.SiH.setGeometry(QtCore.QRect(560, 220, 101, 31))
        self.SiH.setObjectName("SiH")
        self.SiS = QtWidgets.QLabel(self.SubstancesInfo)
        self.SiS.setGeometry(QtCore.QRect(560, 270, 101, 31))
        self.SiS.setObjectName("SiS")
        self.SiG = QtWidgets.QLabel(self.SubstancesInfo)
        self.SiG.setGeometry(QtCore.QRect(560, 320, 101, 21))
        self.SiG.setObjectName("SiG")
        self.SiCp = QtWidgets.QLabel(self.SubstancesInfo)
        self.SiCp.setGeometry(QtCore.QRect(560, 350, 101, 31))
        self.SiCp.setObjectName("SiCp")
        self.EditionSubstance = QtWidgets.QPushButton(self.SubstancesInfo)
        self.EditionSubstance.setGeometry(QtCore.QRect(690, 140, 131, 51))
        self.EditionSubstance.setObjectName("EditionSubstance")
        self.EditNameSubstance = QtWidgets.QLineEdit(self.SubstancesInfo)
        self.EditNameSubstance.setGeometry(QtCore.QRect(52, 124, 611, 81))
        self.EditNameSubstance.setObjectName("EditNameSubstance")
        self.SubstanceStateEdition = QtWidgets.QComboBox(self.SubstancesInfo)
        self.SubstanceStateEdition.setGeometry(QtCore.QRect(690, 220, 131, 41))
        self.SubstanceStateEdition.setObjectName("SubstanceStateEdition")
        self.SubstanceStateEdition.addItem("")
        self.SubstanceStateEdition.addItem("")
        self.SubstanceStateEdition.addItem("")
        self.SaveEditionSubstance = QtWidgets.QPushButton(self.SubstancesInfo)
        self.SaveEditionSubstance.setGeometry(QtCore.QRect(690, 140, 131, 51))
        self.SaveEditionSubstance.setObjectName("SaveEditionSubstance")
        self.NameFormulSubstance = QtWidgets.QLabel(self.SubstancesInfo)
        self.NameFormulSubstance.setGeometry(QtCore.QRect(56, 130, 601, 71))
        self.NameFormulSubstance.setObjectName("NameFormulSubstance")
        self.idsubstance = QtWidgets.QLabel(self.SubstancesInfo)
        self.idsubstance.setGeometry(QtCore.QRect(690, 30, 131, 17))
        self.idsubstance.setObjectName("idsubstance")
        self.CancleEditionSubstance = QtWidgets.QPushButton(self.SubstancesInfo)
        self.CancleEditionSubstance.setGeometry(QtCore.QRect(690, 60, 131, 51))
        self.CancleEditionSubstance.setObjectName("CancleEditionSubstance")
        self.SubstanceSF = QtWidgets.QLabel(self.SubstancesInfo)
        self.SubstanceSF.setGeometry(QtCore.QRect(366, 270, 191, 31))
        self.SubstanceSF.setObjectName("SubstanceSF")
        self.SubstanceHF = QtWidgets.QLabel(self.SubstancesInfo)
        self.SubstanceHF.setGeometry(QtCore.QRect(366, 220, 191, 31))
        self.SubstanceHF.setObjectName("SubstanceHF")
        self.SubstanceGF = QtWidgets.QLabel(self.SubstancesInfo)
        self.SubstanceGF.setGeometry(QtCore.QRect(366, 319, 191, 21))
        self.SubstanceGF.setObjectName("SubstanceGF")
        self.SubstanceCp = QtWidgets.QLabel(self.SubstancesInfo)
        self.SubstanceCp.setGeometry(QtCore.QRect(366, 360, 191, 21))
        self.SubstanceCp.setObjectName("SubstanceCp")
        self.Formula = QtWidgets.QLabel(self.SubstancesInfo)
        self.Formula.setGeometry(QtCore.QRect(50, 400, 131, 41))
        self.Formula.setObjectName("Formula")
        self.newFomula = QtWidgets.QLineEdit(self.SubstancesInfo)
        self.newFomula.setGeometry(QtCore.QRect(182, 400, 381, 41))
        self.newFomula.setObjectName("newFomula")
        self.NewSubstenced.raise_()
        self.FindSubstancesDb.raise_()
        self.SubstancesInfo.raise_()
        self.System.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1938, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu.menuAction())
        self.label.setBuddy(self.StartTemperatura)
        self.label_1.setBuddy(self.StartPressure)
        self.label_3.setBuddy(self.StartSize)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        item = self.FindSubstances.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Название"))
        item = self.FindSubstances.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Формула"))
        item = self.FindSubstances.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Фаза"))
        item = self.FindSubstances.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Тык"))
        self.ClearFind.setText(_translate("MainWindow", "Очистка"))
        self.FindInfo1.setText(_translate("MainWindow", "Введите формулу"))
        self.FindInfo2.setText(_translate("MainWindow", "Введите название"))
        self.NewSubstanced.setText(_translate("MainWindow", "Добавить\n"
"вещество"))
        self.ReactionCalculation.setText(_translate("MainWindow", "Расчет\n"
"реакции"))
        self.TITLE_2.setText(_translate("MainWindow", "Информация об веществе"))
        self.TextH_2.setText(_translate("MainWindow", "Стандартная энтальпия образования ΔH"))
        self.TextS_2.setText(_translate("MainWindow", "Стандартная энтропия образования S"))
        self.TextG_2.setText(_translate("MainWindow", "Стандартная эн. Гиббса образования ΔG"))
        self.TextCp_2.setText(_translate("MainWindow", "Стандартная мольная теплоемкость Cp"))
        self.SiH_2.setText(_translate("MainWindow", "кДж"))
        self.SiS_2.setText(_translate("MainWindow", "Дж/К"))
        self.SiG_2.setText(_translate("MainWindow", "кДж"))
        self.SiCp_2.setText(_translate("MainWindow", "Дж/К"))
        self.NewSubstanceState.setItemText(0, _translate("MainWindow", "Газ"))
        self.NewSubstanceState.setItemText(1, _translate("MainWindow", "Жидкость"))
        self.NewSubstanceState.setItemText(2, _translate("MainWindow", "Твердый"))
        self.SaveNewSubstance.setText(_translate("MainWindow", "Сохранить"))
        self.CancleNewSubstance.setText(_translate("MainWindow", "Отмена"))
        self.Formula_2.setText(_translate("MainWindow", "Формула"))
        self.Result.setText(_translate("MainWindow", "Вещество\n"
"успешно\n"
"добавленно"))
        self.StartSize.setText(_translate("MainWindow", "1"))
        self.label.setText(_translate("MainWindow", "Температура, К"))
        self.label_1.setText(_translate("MainWindow", "Давление, Па"))
        self.label_3.setText(_translate("MainWindow", "Объем для газа, м3"))
        self.ConstTemeratura.setText(_translate("MainWindow", "Зафиксировать"))
        self.ConstSize.setText(_translate("MainWindow", "Зафиксировать"))
        self.ConstPressure.setText(_translate("MainWindow", "Зафиксировать"))
        self.label_2.setText(_translate("MainWindow", "Начальные значения"))
        self.label_4.setText(_translate("MainWindow", "Конечное значение"))
        self.label_5.setText(_translate("MainWindow", "Введите реакцию"))
        self.Calculation.setText(_translate("MainWindow", "Расчет"))
        self.label_6.setText(_translate("MainWindow", "Результат"))
        self.label_7.setText(_translate("MainWindow", "Изменение Энтальпии:"))
        self.label_8.setText(_translate("MainWindow", "Изменение Энтропии:"))
        self.label_9.setText(_translate("MainWindow", "Изменение энергии Гиббса:"))
        self.label_10.setText(_translate("MainWindow", "Направленность реакции:"))
        self.dH.setText(_translate("MainWindow", "TextLabel"))
        self.dS.setText(_translate("MainWindow", "TextLabel"))
        self.dG.setText(_translate("MainWindow", "TextLabel"))
        self.Kp.setText(_translate("MainWindow", "TextLabel"))
        self.BackCalculation.setText(_translate("MainWindow", "Назад"))
        self.TITLE.setText(_translate("MainWindow", "Информация об веществе"))
        self.backFindDB.setText(_translate("MainWindow", "Назад"))
        self.TextH.setText(_translate("MainWindow", "Стандартная энтальпия образования ΔH"))
        self.TextS.setText(_translate("MainWindow", "Стандартная энтропия образования S"))
        self.TextG.setText(_translate("MainWindow", "Стандартная эн. Гиббса образования ΔG"))
        self.TextCp.setText(_translate("MainWindow", "Стандартная мольная теплоемкость Cp"))
        self.SiH.setText(_translate("MainWindow", "кДж"))
        self.SiS.setText(_translate("MainWindow", "Дж/К"))
        self.SiG.setText(_translate("MainWindow", "кДж"))
        self.SiCp.setText(_translate("MainWindow", "Дж/К"))
        self.EditionSubstance.setText(_translate("MainWindow", "Редактировать\n"
"данные"))
        self.SubstanceStateEdition.setItemText(0, _translate("MainWindow", "Газ"))
        self.SubstanceStateEdition.setItemText(1, _translate("MainWindow", "Жидкость"))
        self.SubstanceStateEdition.setItemText(2, _translate("MainWindow", "Твердый"))
        self.SaveEditionSubstance.setText(_translate("MainWindow", "Сохранить"))
        self.NameFormulSubstance.setText(_translate("MainWindow", "TextLabel"))
        self.idsubstance.setText(_translate("MainWindow", "TextLabel"))
        self.CancleEditionSubstance.setText(_translate("MainWindow", "Отмена"))
        self.SubstanceSF.setText(_translate("MainWindow", "TextLabel"))
        self.SubstanceHF.setText(_translate("MainWindow", "TextLabel"))
        self.SubstanceGF.setText(_translate("MainWindow", "TextLabel"))
        self.SubstanceCp.setText(_translate("MainWindow", "TextLabel"))
        self.Formula.setText(_translate("MainWindow", "Новая формула"))
        self.menu.setTitle(_translate("MainWindow", "А что писать?"))
